### ISSUE TITLE
Turn on/off sink, change logging level without needed to redeploy the app

### ISSUE THREAD

**Issue by Vincent-NET** [Cimpress-MCP/serilog-sinks-awscloudwatch#106]
Hi guys. 

Wanna bring up an old topic some one raised previously. 

The section where the document points out when you configure the library without creating a concrete instance(using appsettings.json), it will cause AWS service client to follow the default credential rules.

### **Requesting feature to allow "args" include access key and secret. hear me out:**
Configure through appsettings.json has great advantage over hard coded concrete class 

1. because configure can reload without shutting down the app, no redeployment, real time. If you write to 5 sinks, you can shut down one just by removing the json section. 
2. and you can change the setting on the log level: for example, you don't want to log debug info to the cloud non-stop, but as soon as you see a fatal, you are able to change to debug level without restarting.

Wanna emphasize: this is a great feature, I am hoping we can expand little bit.

**The limitation is AWS default credential, you are tie to your server, inside AWS might work great(not to mention if someone else take over the default profile). The problem if you have your machine on-premise, in Azure, in a container or anywhere outside AWS, you have to set up AWS credential on that server.**

**Would love to decouple from AWS further, I know you can set up a profile in the json to use and setting the location, but still, you hold your credential somewhere else (setting up on as environment variable also the same situation). and required additional documentation for instruction and remembering it during migration.**

https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/CloudWatchLogs/TCloudWatchLogsClient.html
AWS AmazonCloudWatchLogsClient has a few overload methods. we can use for 

> 
			_var client = cloudWatchClient ?? new AmazonCloudWatchLogsClient();

 

&nbsp; | AmazonCloudWatchLogsClient(string, string) | Constructs AmazonCloudWatchLogsClient with AWS Access Key ID and AWS Secret Key
-- | -- | --
&nbsp; | AmazonCloudWatchLogsClient(string, string, RegionEndpoint) | Constructs AmazonCloudWatchLogsClient with AWS Access Key ID and AWS Secret Key
&nbsp; | AmazonCloudWatchLogsClient(string, string, string) | Constructs AmazonCloudWatchLogsClient with AWS Access Key ID and AWS Secret Key

### **Security aspect:** 
As far as how safe it is, the AWS credential file is plaint text. you can say the same about the appsetting.json, but you can store this value in **Azure Key Vault**, you can store in **AWS using Secret Manager**, you can store them in **AWS Parameter Store**, many way to protect the settings(where likely where you store your database connection string). any of these is better than default location when it's publicly known.

**thank you.**

**Comment by wparad** [comment]
We've been down this road in the past, and I don't think it is a fruitful discussion to repeat it here. However, we want to help you achieve what you are trying to do. What you've shared is a bit about the solution you would like, rather than the problem you are facing.

For instance if the problem is **We are forced to use the default profile**. The solution is set the AWS profile using the `export AWS_PROFILE="profile"` env variable.

If the problem is **How do we dynamically create new clients without restarting the service**, I would say here we should use a **C# Provider** pattern.

It's possible that (for example the latter), isn't supported because of an issue with the library, in that case, let's focus on that. So back to the point on hand, can you explain your context more specifically on what you want to achieve, because naively from my side, it sounds like it would be the right thing for you to actually construct the library in code not `appsettings.json` and this will further be the best and most secure solution since you can resolve the AWS credentials in memory, and construct a `CloudWatchClient` that you can directly pass to the library without needing to do anything special.

**Comment by Vincent-NET** [comment]
hey. thank you for the quick respond.

but hmm, I would think we don't need to create a new client. correct me if I am wrong.

**main goal:** able to turn on/off sink, change logging level without needed to redeploy the app.
**second** is provide another way alternately to aws default credential.

I think both are there, but they can't combine because either you hardcode and customize the aws client creation, but not able to change the log level or turn it off. OR use the appsettings.json but have to fall back on aws default credential.

### 1. able to customize the creation of client.
What I am looking for is to pass the access key and secret to create the `AmazonCloudWatchLogsClient` 
this client can stay on and reuse, not looking to change it's access level to aws

I thought add this with 2 new params on [AwsCloudWatchConfigurationExtension.cs](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/blob/master/src/Serilog.Sinks.AwsCloudWatch/AwsCloudWatchConfigurationExtension.cs)
```
<param name="cloudWatchAcessKey">
<param name="cloudWatchSecret">
```

```
if (!string.IsNullOrWhiteSpace(cloudWatchAcessKey) && string.IsNullOrWhiteSpace(cloudWatchSecret)
{
	cloudWatchClient  = new AmazonCloudWatchLogsClient(cloudWatchAcessKey, cloudWatchSecret);
}
```
before this would do it.
> `_var client = cloudWatchClient ?? new AmazonCloudWatchLogsClient();`



### 2. I think this is already there? let me know if I am wrong here too.

with the help of [serilog-settings-configuration,](https://github.com/serilog/serilog-settings-configuration) I would think you can unregister the sink by not having it in the `"Using":  [ `
now I am having a doubt (I double check on that). but if you don't have the` "WriteTo": [ "serilog-sinks-awscloudwatch"] ` it should stop log going to aws right?

also with `"restrictedToMinimumLevel":`  wouldn't I able to change the log level on the fly without restarting?


Thank you.

**Comment by wparad** [comment]
Okay let's focus on the
> main goal: able to turn on/off sink, change logging level without needed to redeploy the app.

I haven't looked at the serilog documentation, what's the recommendation there on how to do this?

**Comment by Vincent-NET** [comment]
I don't know neither. I would think this will take care of it somehow.

**config.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);**

I have to do some research and experience to see.

anyone know?


thank you.

**Comment by wparad** [comment]
> also with "restrictedToMinimumLevel": wouldn't I able to change the log level on the fly without restarting?

I would expect this to work out of the box. If you increased the minimum log level in your appsettings, and are using `config.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);` then the logger would automatically stop in those situations.

Since you can configure the whole logger in the appsettings, you can already add/remove it to trigger the right behavior, right?

So at that point, I'm not sure what wouldn't be supported.

**Comment by Vincent-NET** [comment]
right. I did mentioned that on the first post. your response making me rethink I might be wrong.

but if you agree, then the second part is to **customize** the `AmazonCloudWatchLogsClientt `so you can just use this.
```

  {
    "Serilog": {
        "Using": [ "Serilog.Sinks.AwsCloudWatch" ],
        "MinimumLevel": "Verbose",
        "WriteTo": [            
            {
                "Name": "AmazonCloudWatch",
                "Args": {
                    "logGroup": "your-app",
                    "logStreamPrefix": "environment/component",
                    "cloudWatchAcessKey": ".............",
                    "cloudWatchSecret": "..............",
                    "restrictedToMinimumLevel": "Verbose"
                }
            }
        ]
    }
  }
```

and I am thinking we just need this code modification in [AwsCloudWatchConfigurationExtension.cs](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/blob/master/src/Serilog.Sinks.AwsCloudWatch/AwsCloudWatchConfigurationExtension.cs)

```
if (!string.IsNullOrWhiteSpace(cloudWatchAcessKey) && !string.IsNullOrWhiteSpace(cloudWatchSecret)
{
	cloudWatchClient  = new AmazonCloudWatchLogsClient(cloudWatchAcessKey, cloudWatchSecret);
}
_var client = cloudWatchClient ?? new AmazonCloudWatchLogsClient();
```

**Comment by wparad** [comment]
Why do you need to have the access key and secret in the appsettings, you can put them in ENV variables or your credentials file and it work find right?

**Comment by Vincent-NET** [comment]
this is from my first post. the idea is to deploy your app and not have to worry about additional set up.

> The limitation is AWS default credential, you are tie to your server, inside AWS might work great(not to mention if someone else take over the default profile). The problem if you have your machine on-premise, in Azure, in a container or anywhere outside AWS, you have to set up AWS credential on that server.
> 
> Would love to decouple from AWS further, I know you can set up a profile in the json to use and setting the location, but still, you hold your credential somewhere else (setting up on as environment variable also the same situation). and required additional documentation for instruction and remembering it during migration.

**Comment by wparad** [comment]
> The limitation is AWS default credential, you are tie to your server, inside AWS might work great(not to mention if someone else take over the default profile). The problem if you have your machine on-premise, in Azure, in a container or anywhere outside AWS, you have to set up AWS credential on that server.

You always have to setup an AWS credentials, and I don't understand what you mean by 
> The limitation is AWS default credential

What is a limitation? What does the default credentials have to do with anything. Why is there a problem if you are not in AWS?

You only need [this code](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html):
```cs
var sourceProfileOptions = new CredentialProfileOptions
{
    AccessKey = "access_key",
    SecretKey = "secret_key"
};
var sourceProfile = new CredentialProfile("source_profile", sourceProfileOptions);
sharedFile = new SharedCredentialsFile();
sharedFile.RegisterProfile(sourceProfile);
```

And again the I'll post the [advice from AWS](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-config-creds-warnings-and-guidelines.html):
> Do NOT put literal access keys in your application files. If you do, you create a risk of accidentally exposing your credentials if, for example, you upload the project to a public repository.

There is a reason we don't support passing in the credentials.

**Comment by Vincent-NET** [comment]
> You always have to **setup** an AWS credentials,

you don't always need to, because there are overload methods let you use the key and secret directly([AWS documentation](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/CloudWatchLogs/TCloudWatchLogsClient.html)).


&nbsp; | AmazonCloudWatchLogsClient(string, string) | Constructs AmazonCloudWatchLogsClient with AWS Access Key ID and AWS Secret Key
-- | -- | --
&nbsp; | AmazonCloudWatchLogsClient(string, string, RegionEndpoint) | Constructs AmazonCloudWatchLogsClient with AWS Access Key ID and AWS Secret Key
&nbsp; | AmazonCloudWatchLogsClient(string, string, string) | Constructs AmazonCloudWatchLogsClient with AWS Access Key ID and AWS Secret Key



> Do NOT put literal access keys in your application files. If you do, you create a risk of accidentally exposing your credentials if, for example, you upload the project to a public repository.

I mentioned it in the first post, they aren't actually in the appsettings.json file, the same way you apply to hide your database connectionstring.

> Security aspect:
> As far as how safe it is, the AWS credential file is plaint text. you can say the same about the appsetting.json, but you can store this value in **Azure Key Vault**, you can store in AWS using **Secret Manager**, you can store them in **AWS Parameter Store**, many way to protect the settings(likely where you store your database connection string). any of these is better than default location when it's publicly known.

your example is the point of limitation. that code goes to all applications. and maybe it doesn't bother some people, but it's a huge risk and the **irony is AWS suggests don't put the access key in your application files. but they tells you to put (multiple access keys) in a public known(~/.aws/credential %USERPROFILE%\.aws\credentials) place AND in plaint text.** 

sum up my original point is having an alternative option that not rely on AWS profile.

**Comment by wparad** [comment]
You're missing my point. You need to inject yyour credentials somewhere. I'm asking why you don't do it app side? The one solution I think we can't support is allowing the credentials in the appsettings, so pick another place, and we'll help you make that work.

**Comment by Vincent-NET** [comment]
anyway. thank you for your response, and I do appreciated you taking your time to answer questions.

I do see you points, and I think you made up your mind. I'll think of some other options. 

your point for example: mssql sink use this. and the `User Id=myUsername;Password=myPassword`

you could replace that with `Integrated Security=SSPI` but you can't when you are out side of the domain. But never the less, it's about how you manage the credential.

by the way, I don't have problem or want to complain about AWS, I am just trying to find an **alternative** and I do understand ENV and AWS config.

```
  "Serilog": {
    "MinimumLevel": "Information",
    "WriteTo": [
      {
        "Name": "MSSqlServer",
        "Args": {
          "connectionString": "Server=myServerName\myInstanceName;Database=myDataBase;User Id=myUsername;Password=myPassword;",
          "tableName": "Log"
        }
      }
    ]
  }
```

thank you.

**Comment by wparad** [comment]
I'm going to close this, but I want to make sure we aren't missing an obvious option here. Unlike the mssql logger, you do have 4 options:
* credentials file (either default or custom)
* encrypted AWS profile store
* env variables
* SAML registered Active Directory Federation Services through the SDK

Honestly, the missing option which would be the best is what the other AWS SDKs provide, and that's the ability to update the credentials for all of AWS using `AWS.config.update`. It used to the be the case you could update the credentials chain, but they have since removed that functionality.

**Comment by Vincent-NET** [comment]
sure you can close it. just wanna add note here for any change of mind in the future. 

and yes, there are alot of options, but want to point out how other sinks pass the credential through the service client creation.

Sinks don't have to follow the same pattern, some of the sinks don't have that many options like AWS. but would be nice if this one has one more option.

serilog-sinks-mongodb

```
    "WriteTo": [
      { 
      	"Name": "MongoDBBson", 
        "Args": { 
            "databaseUrl": "mongodb://username:password@ip:port/dbName?authSource=admin",
            "collectionName": "logs",
            "cappedMaxSizeMb": "1024",
            "cappedMaxDocuments": "50000"
            }
       }
```

serilog-sinks-postgresql

```
"Serilog": {
    "Using": [ "Serilog.Sinks.PostgreSQL.Configuration" ],
    "MinimumLevel": "Debug",
    "Enrich": [ "WithMachineName" ],
    "WriteTo": [
      {
        "Name": "PostgreSQL",
        "Args": {
          "connectionString": "LogsDb",
          "tableName": "table_name",
          "needAutoCreateTable": true
        }
      }
    ]
  },
  "ConnectionStrings": {
    "LogsDb": "User ID=serilog;Password=serilog;Host=localhost;Port=55432;Database=serilog_logs"
  },
```
serilog-sinks-seq

```
        "WriteTo":
        [{
            "Name": "Seq",
            "Args":
            {
                "serverUrl": "http://localhost:5341",
                "apiKey": "yeEZyL3SMcxEKUijBjN",
                "controlLevelSwitch": "$controlSwitch"
            }
        }]
```

**Comment by szakula-hinda** [comment]
@wparad Can you please reconsider this change to support the following values in the sink Args:

- AccessKey
- SecretKey
- Profile
- Region


Honestly, this is a huge oversight for this sink and from reading the documentation, it seems it has been avoided despite many people indicating a desire and a need for it. The claim that it is "not secure" is inaccurate. Of course, if the developers using it do not follow best practices and publish private credentials to a public github repo, then yes that can be a vulnerability. That is a human error, not a design flaw. The same can be said about suggested method of using an AWS Credentials File - someone can publish this file containing the credentials to the same repo. Additionally, if developers are comfortable putting the credentials in appsettings.json, they should have that choice in addition to the other options already supported.

A proper implementation using this sink would use CI/CD pipelines and the release pipeline would have release variables with the proper values for each environment that get transformed into appsettings.json during deployment. The actual values would be stored in the release pipeline for each environment, not in the repo source, and furthermore variables can be stored securely such as in Azure Key Vault.

**Comment by wparad** [comment]
sure it is a human error, but it's our responsibility being open source maintainers to encourage good security practices. If there is a legitimate need to inject AWS credentials into the running process, AWS already has **best practice** recommendations on this, that don't involve this library. And while I 100% there are ways to do it more secure if necessary, and clearly you are more than capable of determining how to do this, these aren't the common use cases.

> The actual values would be stored in the release pipeline for each environment, not in the repo source, and furthermore variables can be stored securely such as in Azure Key Vault.

So this actually isn't the best idea, exposing AWS credentials to your CI/CD is a bad idea, it's better to save them directly in SSM or SecretManager, or even better to encyrpt using KMS and decrypting only at runtime. But we aren't here to debate the best practices for credentials management.

However, it's always possible that there is a some use case that AWS didn't think of, and that needs to be improved. Feel free to detail the use case and why the appropriate fix would be for this library (and also therefore every library in existence) to implement it and not for the fix to be in the AWS C# SDK and it is something we can definitely consider. Remember injecting credentials into the AWS SDK is already easy using the strategy you suggested, if for some reason they can't be, that would be great information for us to know, so please share.
