### ISSUE TITLE
How to set sink default log level to what is set for Serilog

### ISSUE THREAD

**Issue by amin-sage** [Cimpress-MCP/serilog-sinks-awscloudwatch#107]
Is there a way to just follow the log level set in Serilog setup code for sink as well instead of hard coded value? Thanks.

**Comment by wparad** [comment]
All the log levels work on the following premise:
> Only log the highest level set.

Log levels can be set in three places:
* Default minimum log level Serilog: `.MinimumLevel.Debug()`
* Logger override in Serilog configuration `restrictedToMinimumLevel`
* `CloudWatchOptions` minimum log level

You don't need to set any of these, and then minimum will be the higher of Serilog's default and this library's default.

Is that not what you are seeing?

**Comment by amin-sage** [comment]
Thanks for your reply, so if I want to control with Default MinimumLevel set for Serilog in appsettings I should set `CloudWatchOptions` to like Verbose?

**Comment by wparad** [comment]
Yeah, that should work.

**Comment by amin-sage** [comment]
Thanks :)
