### ISSUE TITLE
Is .Net Framework 4.8 supported?

### ISSUE THREAD

**Issue by Kayes-Islam** [Cimpress-MCP/serilog-sinks-awscloudwatch#108]
We are thinking of using this package for our Asp.net Framework 4.8 application. But the readme says:
>It supports .NET Core (.NET Framework 4.5 is deprecated and no longer supported)

I noticed that the package targets NETStandard 2.0, so I could potentially use it for our asp.net Framework 4.8 application. Is asp.net framework 4.8 supported?

**Comment by wparad** [comment]
Best thing to do is try it out, if it doesn't work we'll happily toke a PR to resolve any issues.
