### ISSUE TITLE
PeriodicBatching moving away from inheritance based API

### ISSUE THREAD

**Issue by ChadyG** [Cimpress-MCP/serilog-sinks-awscloudwatch#111]
See:
https://github.com/serilog/serilog-sinks-periodicbatching/pull/56

Some other dependencies are now pointing to the 3.0.0 release of this, which breaks any code inheriting directly from PeriodicBatchingSink.  There is a 3.1.0 release that returns the inheritance, but as the old API is obsoleted any code inheriting from this needs to be updated to avoid conflicts in the future.

**Comment by wparad** [comment]
I think the easiest thing here is to just copy the `PeriodicBatchingSink` into this library, and release a new version by removing the dependency. A PR would be welcome on this.

**Comment by genoher** [comment]
I have never made a pull request.
I will make a pull request after testing/validating the changes I have made to the code.
There is a constructor that I had to change and I don't know if I did it right...
They have to provide me with an amazon cloud watch user to be able to test it. 
I suppose that tomorrow I will have it, and I will be able to do some test.

Some of the changes I have made are the following:
- Change netstandard2.0 to net6.0
- Update package reference 'Serilog.Sinks.PeriodicBatching' from '2.*' to '3.1.0'
- Update file appveyor.yml property version from '4.0' to '5.0'
- Update file Global.json property sdk version from '2.1.401' to '6.0.311"'
- Change implementation of CloudWatchLogSink. Modify PeriodicBatchingSink inheritance by interfaces IBatchedLogEventSink and ILogEventSink.

After testing it and confirming that it works correctly, I will make a pull request.

PD: Sorry if my English is not correct, I have used the google translator.

**Comment by wparad** [comment]
> I have never made a pull request. I will make a pull request after testing/validating the changes I have made to the code. There is a constructor that I had to change and I don't know if I did it right... They have to provide me with an amazon cloud watch user to be able to test it. I suppose that tomorrow I will have it, and I will be able to do some test.
> 
> Some of the changes I have made are the following:
> 
> * Change netstandard2.0 to net6.0
> * Update package reference 'Serilog.Sinks.PeriodicBatching' from '2.*' to '3.1.0'
> * Update file appveyor.yml property version from '4.0' to '5.0'
> * Update file Global.json property sdk version from '2.1.401' to '6.0.311"'
> * Change implementation of CloudWatchLogSink. Modify PeriodicBatchingSink inheritance by interfaces IBatchedLogEventSink and ILogEventSink.
> 
> After testing it and confirming that it works correctly, I will make a pull request.
> 
> PD: Sorry if my English is not correct, I have used the google translator.

Please don't do any of those things. Instead just copy the whole version 2.0 of the Serilog.Sinks.PeriodicBatching library into this library and remove the dependency.

**Comment by jackfrosty908** [comment]
Would like to add to this I also have encountered the same issue. At the moment we are removing the Datadog sink and instead using the [Datadog Forwarder](https://docs.datadoghq.com/logs/guide/forwarder/?tab=cloudformation) to get CloudWatch logs into Datadog.

**Comment by wparad** [comment]
This is being fixed in #115
