### ISSUE TITLE
Package version 4.0.180 has incorrect dependencies.

### ISSUE THREAD

**Issue by rexsacrorum** [Cimpress-MCP/serilog-sinks-awscloudwatch#117]
It requires:
AWSSDK.CloudWatchLogs ≥ 4.0.180
Serilog ≥ 4.0.180
Serilog.Sinks.PeriodicBatching ≥ 4.0.180

**Comment by wparad** [comment]
Why do you say that. It shouldn't be the case, the library has been tested with a number of different versions.

**Comment by rexsacrorum** [comment]
> Why do you say that. It shouldn't be the case, the library has been tested with a number of different versions.

You can't install the package because it requires non existing versions of packages.
For example, latest stable version of Serilog is 3.0.1

Just check dependescies for latest and previous package.
https://www.nuget.org/packages/Serilog.Sinks.AwsCloudWatch#dependencies-body-tab

**Comment by wparad** [comment]
What happens when you try to install the package?

**Comment by rexsacrorum** [comment]
> What happens when you try to install the package?

Install fails because it can't find nonexisting packages.

<img width="1176" alt="image" src="https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/assets/216757/fa7499d7-f5d0-4981-a7fc-a78800467692">

It's obviously a mistake in the package manifest because versions of all dependencies are the same as this package  - 4.0.180

**Comment by wparad** [comment]
My best guess is that your version of nuget/dotnet isn't correctly handling the version string. From the documentation: https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#floating-version-resolutions These are valid:
![image](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/assets/5056218/5107627f-986d-4a65-939c-ed4c90db2127)


In any case, I've created #118 to not use the floating star for these cases where the nuget package repository/nuget tool is out of spec with the documentation.
