### ISSUE TITLE
Serilog.Sinks.AwsCloudWatch with latest AWSSDK.Core  (>= 3.7.302.14 && < 4.0.0)

### ISSUE THREAD

**Issue by ddx-marquez** [Cimpress-MCP/serilog-sinks-awscloudwatch#127]
Hi,

I have a few aws sdk dependencies (S3, secret manager) that I keep up to date with the latest versions. 

When I try to install the latest version of Serilog.Sinks.AwsCloudWatch version 4.0.182 it indicates an old dependency for AWSSDK.CloudWatchLogs version 3.5.0.9 (current version to this date is 3.7.304.7) , this makes it so it only works with AWSSDK.Core (>= 3.5.1.7 && < 3.6.0).

My app works with AWSSDK.Core (>= 3.7.302.14 && < 4.0.0) , is there an update or pre-release available to work with AWSSDK.CloudWatchLogs 3.7.304.7 which is compatible with latest AWSSDK.Core?

This is a production app and we cannot downgrade the versions.

**Comment by josh-houseworks** [comment]
Hello, any updates on this? I am also running into the same issue while trying to use masstransit.

**Comment by wparad** [comment]
@thoean

**Comment by thoean** [comment]
Sigh... I'm trying to get rid of the old Appveyor webhook to only use the Github action. Everything is technically removed, but Github still believes, it's there and blocks successful builds. I'm working with support to get this removed.
If anyone has ideas on how to solve this, I'm all ears.

**Comment by wparad** [comment]
1. go to https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/settings/branches
2. Click on Edit
![image](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/assets/5056218/a795d50e-4e83-4f84-91f6-f25e88fab5b0)

3. Go to the status checks configuration and remove `AppVeyor`

![image](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/assets/5056218/b562dc3c-75c8-44ad-8f29-cd7925baf734)

**Comment by thoean** [comment]
Oh wow - that worked.. can you approve https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/pull/125 to ensure the whole pipeline including publishing a new version works? Thanks a lot.

**Comment by wparad** [comment]
> Oh wow - that worked.. can you approve #125 to ensure the whole pipeline including publishing a new version works? Thanks a lot.

Done.
