### ISSUE TITLE
Request for Update on Compatibility with Latest AWSSDK.Core

### ISSUE THREAD

**Issue by BrandonCaddowYoung** [Cimpress-MCP/serilog-sinks-awscloudwatch#136]
This is more of a question than an issue.

Currently, your project references AWSSDK.CloudWatchLogs 3.5.0.9 which references AWSSDK.Core (>= 3.5.1.7 && < 3.6.0). In other words; Serilog.Sinks.AwsCloudWatch 4.2.25 -> AWSSDK.CloudWatchLogs 3.5.0.9 -> AWSSDK.Core (>= 3.5.1.7 && < 3.6.0)

Given that the latest version of AWSSDK.Core is 3.7.303.19, could you please inform me when you plan to release an update of Serilog.Sinks.AwsCloudWatch that is compatible with this newer version of AWSSDK.Core?

Thanks in advance,
Brandon

**Comment by wparad** [comment]
> Currently, your project references AWSSDK.CloudWatchLogs 3.5.0.9

It doesn't. It specifically references all versions greater than or equal to 3.5.09:

```xml
<PackageReference Include="AWSSDK.CloudWatchLogs" Version="[3.5.0.9,)" />
```

So it already supports the latest version of AWSSDK.Core.

**Comment by jyee-ctm** [comment]
For those who have forgotten how to handle this (_with the help of chatgpt_), here's the solution:

To enforce the installation of `Serilog.Sinks.AwsCloudWatch` to use the latest version of `AWSSDK.CloudWatchLogs`, you can update the PackageReference for `AWSSDK.CloudWatchLogs` in your project file to allow any version.

Here's an example of how you can update the PackageReference for AWSSDK.CloudWatchLogs:

```csproj
<PackageReference Include="AWSSDK.CloudWatchLogs" Version="*" />
```

This will allow any version of `AWSSDK.CloudWatchLogs` to be installed, including the latest version.

After updating the `PackageReference`, you can run `dotnet restore` to update the dependencies and resolve the version conflict.
