### ISSUE TITLE
(Suggestion) Simplify PutLogEvents calls as they no longer require sequence token

### ISSUE THREAD

**Issue by VadymLevkovskyi** [Cimpress-MCP/serilog-sinks-awscloudwatch#142]
`AWS CloudWatch` [PutLogEvents](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html) no londer requires specific `sequence token` (see note from [API documentation](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html#API_PutLogEvents_RequestSyntax))

Thus code of `PeriodicBatchingSinkImplementationCallback` might be slightly made more clean.

See possible implementation in #143

**Comment by thoean** [comment]
This issue got resolved via pull request #143.
