### ISSUE TITLE
Framework 4.5.1 or Standard Library 1.2 Support

### ISSUE THREAD

**Issue by aggieben** [Cimpress-MCP/serilog-sinks-awscloudwatch#19]
I have an application in which I would like to use this package; however, because the target frameworks are limited to `net461` and `netstandard1.5`, I cannot.  We are using .NET Core, but are having to stay on the Mono runtime (`net451`) for the time being because of blocking dependencies.  Is there any particular reason that the target framework versions need to be set so high for this package?  

It seems to me that it probably doesn't, in particular because the TFM for `dnx451` was only dropped at the RC1 stage.

For our purposes, `netstandard1.2` (or `net451`).

**Comment by thoean** [comment]
The [AWS SDK](https://www.nuget.org/packages/AWSSDK.Core/) depends on `netstandard1.3`, so you might have an indirect dependency that's higher than what you need anyways. There's however no particular reason for not including `net451` from our side.

May I suggest that you come up with a pull request that'd run on your system and continues to be compatible with other usages? I can retest that towards our systems (most of them have upgraded to the latest versions of various dependencies).

Thanks!

**Comment by aggieben** [comment]
Perfect.  I anticipate submitting something today.

**Comment by aggieben** [comment]
In trying to build/run the test project, I did a `dotnet restore` in `test\Serilog.Sinks.AwsCloudWatch.Tests` and it failed like this:

![image](https://cloud.githubusercontent.com/assets/1321/19277274/c0946188-8f9e-11e6-8f23-d1c5679779e0.png)

**Comment by aggieben** [comment]
This is addressed in PR #20
