### ISSUE TITLE
Use ILogger to log error rather than Console.WriteLine

### ISSUE THREAD

**Issue by aggieben** [Cimpress-MCP/serilog-sinks-awscloudwatch#24]
At https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/blob/master/src/Serilog.Sinks.AwsCloudWatch/CloudWatchLogSink.cs#L96 the exception is being written to the console.  It's quite noisy if the AWS credentials are misconfigured - could this be written using the `ILogger` instance instead?

**Comment by nblumhardt** [comment]
Serilog sinks can use `Serilog.Debugging.SelfLog.Write()` for this 👍
