### ISSUE TITLE
Enable CloudWatch Sink through configuration file

### ISSUE THREAD

**Issue by SubmittaBrian** [Cimpress-MCP/serilog-sinks-awscloudwatch#28]
I'd love to be able to drop in this sink [by adding it to `app.config`](https://github.com/serilog/serilog/wiki/AppSettings), but I don't think Serilog currently supports nested deserialization (or I haven't been able to make it work).

Would you consider adding an overload to `AwsCloudWatchConfigurationExtension.AmazonCloudWatch` that takes options and credentials as top-level parameters?

This would allow me to extend my prod `app.config` file like:
```xml
<appSettings>
    <!-- Log everything to Stackify for historical debug by DevOps-->
    <add key="serilog:using:Stackify" value="Serilog.Sinks.Stackify" />
    <add key="serilog:write-to:Stackify" />
    <add key="serilog:write-to:Stackify.restrictedToMinimumLevel" value="Debug" />

    <!-- Log Fatal errors to CloudWatch for real-time alert distribution e.g. pager duty systems -->
    <add key="serilog:using:AmazonCloudWatch" value="Serilog.Sinks.AwsCloudWatch" />
    <add key="serilog:write-to:AmazonCloudWatch"/>
    <add key="serilog:write-to:AmazonCloudWatch.logGroupName" value="myLogGroup/myEnvironment"/>
    <add key="serilog:write-to:AmazonCloudWatch.minimumLogEventLevel" value="Fatal"/>
    <add key="serilog:write-to:AmazonCloudWatch.awsRegion" value="us-west-1"/>
    <add key="serilog:write-to:AmazonCloudWatch.awsAccessKey" value="*****"/>
    <add key="serilog:write-to:AmazonCloudWatch.awsSecretKey" value="*****"/>
</appSettings>
```

**Comment by wparad** [comment]
Sounds like a good idea, feel free to make a PR.

**Comment by wparad** [comment]
For the record, I think the problem that the constructor requires parameters, we probably just need an empty constructor, and then we'll be good.
