### ISSUE TITLE
Allow custom LogStreamName

### ISSUE THREAD

**Issue by hzhengran** [Cimpress-MCP/serilog-sinks-awscloudwatch#35]
Current `DateTime + HostName + GUID` makes it hard to find logs when have multiple servers in one logGroup. So it will be nice if we can custom the `LogStreamName` when creating the logger.

**Comment by wparad** [comment]
@hzhengran, sounds like a good idea.  We'd welcome a pull request to improve that.  I would recommend adding in a property to `CloudWatchSinkOptions` and then consuming it at the [CloudWatchSink.UpdateLogStreamName](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/blob/master/src/Serilog.Sinks.AwsCloudWatch/CloudWatchLogSink.cs#L28).

**Comment by hzhengran** [comment]
PR #36 added this feature. So close this issue.
