### ISSUE TITLE
Add option for creating log groups

### ISSUE THREAD

**Issue by tbuckmaster** [Cimpress-MCP/serilog-sinks-awscloudwatch#42]
Would like to add a setting to optionally create the specified log group, instead of always creating it.
This would cut down on the level of permissions required, (no longer need DescribeLogGroups and CreateLogGroup)

**Comment by thoean** [comment]
Interesting idea. While I agree that you need less permissions, how do you automate that part as part of your deployment? While it's definitely possible, I feel like that's complicating matters without large benefit except in a situation of a large, shared account where you need to invest into managing fine grained permissions.

That said, do you intend to create a pull request?

**Comment by tbuckmaster** [comment]
The scenario I am trying to address is an application that is installed in a customer's environment that I don't have control over and we are providing access keys to them.  I don't want to expose that level of permissions.

And yes, I intend to create a pull request for this change soon.

**Comment by wparad** [comment]
Closed via #43
