### ISSUE TITLE
Silent failures writing to cloudwatch log groups

### ISSUE THREAD

**Issue by lamontadams** [Cimpress-MCP/serilog-sinks-awscloudwatch#44]
Hi,

I'm seeing the sink silently fail to log to a cloudwatch log group. We're generating temporary credentials via  the security token service. What I'm seeing happen is serilog will successfully create a log stream, but no messages get written, no exceptions are thrown, and nothing is written to the selflog. 

If I set up a PutLogEvents call using the same credentials, stream, group via the same client I hand to serilog, it will succeed. 

Repro code (with secrets removed) written against Serilog 2.5 and Serilog,Sinks_AwsCloudWatch 2.0.73 is attached.
[Program.txt](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/files/1264984/Program.txt)

Edit - as a matter of fact, running that sample as-is with invalid security credentials will also reproduce it. The attempt to write directly using the client will throw an exception, the call to Log.Logger.Debug will fail silently with nothing in the selflog and no exceptions thrown.

-Lamont

**Comment by wparad** [comment]
It could be there are some self log statements missing.  To help specifically with your problem, could also post the contents of `ConstantLogStreamNameProvider`.  My guess would be that it may not output a json string, and CloudWatch is dropping it on the floor.

**Comment by thoean** [comment]
Additionally: How long are you waiting before ending the program? The CloudWatchSink inherits from `PeriodicBatchingSink`, and defaults to send logs after 10 seconds or 100 messages, whatever comes first.

That said, did you wait at least 10 seconds before closing your program? I just wanted to rule out that problem.

**Comment by lamontadams** [comment]
HI guys,

Thanks for the responses. To be clear, there are two things I'm seeing:
1. When configured with correct credentials, the Cloudwatch sink is not posting messages to cloudwatch, while an SDK cloudwatch logs client is able to Put messages using the same credentials.
2. When configured with invalid credentials (so it would not be able to describe or create log streams), the Cloudwatch sink fails silently, while an SDK cloudwatch client throws an exception using the same credentials.

I feel like in #2 at least, something should be written to the self log, regardless of test duration or what batch settings are specified by CloudWatchSinkOptions properties. Am I wrong there?

I'm confused by you asking for ConstantLogStreamNameProvider source. That's provided by the Serilog.Sinks.AwsCloudwatch package, so it's a built-in type? 

Other sinks (console and rolling file) are working correctly for us in production, so this doesn't feel like a problem with configuration, seems to be something in the sink itself. I also periodically see the rolling file log sink complaining about locking issues in the selflog, so the selflog is working in production. The Cloudwatch sink is just not writing anything to it.

In production, we've had code running for an hour or more generating thousands of messages with no messages appearing in Cloudwatch, but they do show up in our other sinks.  We've also run for extended periods of time with invalid credentials (we didn't know they were invalid, stumbled up on that while researching). Nothing ever appears in the self log in either case. 

Thanks.

**Comment by thoean** [comment]
Serilog's [default minimum level](https://github.com/serilog/serilog/wiki/Configuration-Basics#minimum-level) is `Information`. You're sending a `Debug` message, so it didn't even get to the sink.

Once I took your code, changed it to `Information`, an error (from `Selflog`) showed up on the console since I had invalid credentials.

One correction from my previous statement: The `PeriodicBatchingSink` immediately sends the first message, especially to allow detecting problems with a sink's setup early. For further messages, the timeout / batch size parameters matter. That said, for your repro, you see the failure almost immediately (it takes roughly 1 second until the Amazon Client figures out that there were invalid credentials).

If you actually want to send messages with log level debug (or even verbose), you can change that in the logger configuration. For example to debug::

```cs
var configuration = new LoggerConfiguration().MinimumLevel.Debug().WriteTo.AmazonCloudWatch(sinkOptions, client);
```

**Comment by lamontadams** [comment]
Yeah, I thought of that but didn't update my posted repro code. I've been
testing with logging error messages, so that's not the real problem.

After messing around with it further for a couple of hours, what I
eventually figured out is that if someone sets BatchSizeLimit to 0, no
messages are ever sent by the sink (which was the problem in our production
code). If you try to wait out the period delay via Thread.Sleep (or
apparently with a Console.ReadLine()) no messages will be sent by the sink,
even with BatchSizeLimit > 0.

I'm not sure I've seen the behavior you describe with the first message
being sent immediately with BatchSizeLimit >0 but I've run so many
possibilities today I could be mis-remembering.

**Comment by wparad** [comment]
@lamontadams, can I get a confirmation that the problem was configuration, and we can resolve that confusion by #45?

**Comment by jasonwadsworth** [comment]
I'm seeing this same issue. My chief concern is that once it gets into a state of not working it doesn't seem to fix itself. Once I lose logs it doesn't recover until the process is restarted.

**Comment by wparad** [comment]
@jasonwadsworth, I am going to close this issue, because I have a suspicion it is a different problem.  Would you be able to create a new issue and add reproduction code so that we can better investigate the issue?
