### ISSUE TITLE
Logging appears to stop

### ISSUE THREAD

**Issue by tmschlot** [Cimpress-MCP/serilog-sinks-awscloudwatch#46]
# Problem

When attempting to use this sink, we found cases when logging would appear to stop.  

# Investigation

There was no indication as to what the issue was in our logs/code, and we didn't have Serilog's [SelfLog](https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics) enabled at the time of the occurrences.  Since we enabled the SelfLog in our services, we haven't seen the behavior described.  

We knew this was still an issue, though, so we reviewed the sink's code itself to see if there was any indication of what might be happening in it.  Initially, the code seemed fine, but the exception handling seemed a bit lacking.  Essentially, if something/anything fails, a new log stream is created and the batch is dropped.  So could we be dealing with a failure condition -- or multiple conditions -- that would cause our logged events to continually be dropped?  Yes, we could.  

AWS CloudWatch Logs has [limits](http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html) for at least a few things that we could be hitting with the events we're logging.

1) Event size -- 256 KB is the maximum size of a single event.  We've received some messages we log that do exceed this limit.  So the likelyhood of hitting this limit is the same as the likelyhood of receiving a message that large, which happens infrequently but definitely not "never."  
2) Batch size -- 1 MB is the maximum size of a batch of events.  If we're using the default BatchSizeLimit of 100, that means the mean size of our log events must be 10 KB.  As I've mentioned, we have some messages we log that exceed the 256 KB limit, and the mean size of events we log is under 10 KB, but we do have a lot of variation in size, so the likelyhood of hitting this limit is determined by...
    1) if we attempt to log a larger message within a batch or 
    2) if we fill an entire batch within the configured Period, in which case the mean size of events in the batch could exceed 10 KB.  We're using 10 seconds for the Period, at current, so more activity increases the likelyhood of this happening.
3) PutLogEvents -- Simply, you can only call PutLogEvents up to 5 times per second per stream.  The [PeriodicBatchingSink](https://github.com/serilog/serilog-sinks-periodicbatching) provided by Serilog obviously does not enforce this restriction, and instead, attempts to send up to the number of messages specified in the BatchSizeLimit parameter until the queue of logged events is empty (as fast as it can).  Thus, the concrete implementation of the PeriodicBatchingSink (this sink) is responsible for backing off.  We have periods where we log thousands of events in the configured 10 second Period, so our only chance for not hitting this limit when we're experiencing this traffic spike is to rely on the latency of the call to be enough to not cause throttling (and an Exception).  

Knowing what the issues were, I was able to write a [sample application](https://github.com/tmschlot/LargeMessages) that reproduces at least a couple of the issues stated.  My results in running this application are...

1) 26 log streams are created.  Only one of which has any events in it.
2) Only 3-6 events were logged to CloudWatch Logs of the 2600 that were written to Serilog.  

# Conclusion

The existing strategy for sending events and handling failures should be replaced with a strategy that...

1) Does not create a log stream for every exception encountered.
2) Retries failed batches.
3) Truncates individual events at 256 KB.
4) Limits a batch of events sent to CloudWatch Logs to 1 MB.
5) Throttles requests so that it sends no more than 5 requests to a log stream per second.

**Comment by wparad** [comment]
@tmschlot, thanks for looking into these problems.  I agree these are some serious issues from a usability standpoint, and either more intelligent logic or explicit failures would be better than the current state.  Some of these might be easy to address, but also could be bigger digs.  We would gladly accept a PR solving any of these.  I'm a little hesitant on doing `1`, if the others are solved.  But logging that the exception happened is also necessary.

**Comment by tmschlot** [comment]
@wparad Thanks for your response and openness to make some changes.  

I've been looking at the [PeriodBatchingSink](https://github.com/tmschlot/serilog-sinks-periodicbatching/blob/dev/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PeriodicBatchingSink.cs) a bit to make sure I understand how it works, and two things stick out that I think will make it easy enough to work with.  
1) It awaits its call to the EmitBatchAsync method, so the execution is serial.  
2) It only sets a single timer _after_ attempting to emit the batch, as opposed to having the timer tick off at regular intervals.

It also has retry logic built-in (if an exception is thrown from the EmitBatchAsync method), but I don't think it's useful since it couples the starting point for the exponential backoff with the given batch-emitting Period.  Personally, I would want to configure these two things with very different values.  For example, I may want to emit the batch every 10 seconds, but I would want retries to backoff starting at 500 ms or so.

There are a few other restrictions that aren't in my previous findings that I also recall dealing with before.  Find them [here](http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html).  I don't think they would necessarily apply to the scenario I'm currently faced with, but the changes I'd like to make should still take those into consideration.  (Ex: Old log events, future log events, events in a batch cannot span more than 24 hours, etc.)  

So the algorithm I am proposing for the EmitBatchAsync method ends up with the following high-level steps...
1. EnsureIntialized -- still need to do this, though some logic might make sense to move around a little once everything else is finished
2. Order the events and render the event messages -- essentially what's already there, though we should trim the messages to a length of 256 KB (possibly minus 26 bytes)
3. Create sub-batches that adhere to all of the restrictions of a batch sent in the PutLogEvents call
    1. all events within 24-hour span
    2. maximum of 10,000 events in the sub-batch
    3. maximum sub-batch size of 1 MB
4. Attempt to send all sub-batches to CloudWatch Logs in a retry-able loop (configured via the options to make n attempts)
    1. If we get a _ServiceUnavailableException_, we could either a) throw it and use the PeriodicBatchingSink's retry logic or b) use internal retry logic.  I'd lean towards the internal retry logic.
    2. If we get a _ResourceNotFoundException_, we should ensure the log group and log stream exist and retry.  
    3. If we get an _InvalidParameterException_, we should simply log the issue and eat the sub-batch.  I'm not sure what else we can do unless we know more details about what exactly happened.
    4. If we get an _InvalidSequenceTokenException_ or a _DataAlreadyAcceptedException_, we should update the stream's sequence token and retry, but we don't need to create a new stream.
    5. If we get some other exception, we log it and eat the sub-batch.
    6. Otherwise, the sub-batch succeeded, so we throttle the request (to make sure we don't send more than 5 requests to the stream per second) and move on to the next sub-batch until they're all processed.

All failure cases should have plenty of logging to the SelfLog, so end-users can understand what's going on.  And any time we have a non-null value for the RejectedLogEventsInfo property on the response, which is rare, we should log that information.  

Does this sound like a viable solution to you?  If so, I can start on a PR.  If not, please let me know what parts you are concerned about.

**Comment by wparad** [comment]
I think that is a good idea.  Can I ask that the upgrade to csproj and each of the major changes are separate PRs.  I want to be able to have this work separated so I can validate individual pieces.

On the csproj update, you'll have to update the [build script](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/blob/master/build.ps1) as well to target them instead of the xproj.  Here is an example from [another project](https://github.com/Cimpress-MCP/dotnet-core-httputils/blob/master/build.ps1) that was also upgraded in a similar way.
