### ISSUE TITLE
Add Message Truncation Handler

### ISSUE THREAD

**Issue by zsims** [Cimpress-MCP/serilog-sinks-awscloudwatch#52]
Per the maximum message size of CloudWatchLogs, large events will be trimmed before submitting the batch: https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/blob/ca53ac5c7e0fd71c71f32ab5be8f78f9d761fb8c/src/Serilog.Sinks.AwsCloudWatch/CloudWatchLogSink.cs#L328-L333

This causes problems with structured logs (e.g. JSON) as this results in submitting malformed JSON to CloudWatchLogs. Propose adding an option to "drop" large messages rather than trimming them to length. We certainly have some live cases that bump up against the 256KB message limit (which I acknowledge is huge 😆).

**Comment by wparad** [comment]
CloudWatch doesn't need to have JSON as its input.  In that case it might make sense to have some sort of handler parameter which could provide an alternate strategy.  It probably isn't a simple change, but I think it makes sense to leave it here.

**Comment by wparad** [comment]
We'll happily toke a PR to implement this, but sans that I'm closing this issue.
