### ISSUE TITLE
Setting log event renderer from appsettings

### ISSUE THREAD

**Issue by dillan-p** [Cimpress-MCP/serilog-sinks-awscloudwatch#56]
Looked around but can't find a valid answer. I've made a custom json renderer to send content to cloudwatch. I would like to set the 'logEventRenderer' to this class using appsettings rather than code. Looking at the source, something like this should be possible:

`<add key="serilog:write-to:AmazonCloudWatch.logEventRenderer" value="{namespace}.JsonLogMessageRenderer" />`

However, I keep getting getting an 'InvalidCastException' `'Invalid cast from 'System.String' to 'Serilog.Sinks.AwsCloudWatch.ILogEventRenderer'.'`

How should I pass my class through appsettings? Thanks

**Comment by wparad** [comment]
@dillan-p, as stated in some of the other issues in this repo, such as [this one](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/pull/30#issuecomment-290657252), we have no idea what the exact right way to do this is.  Does Serilog even support this behavior?  We are happy to add functionality to help if there is a straightforward way to support, but I'm not sure there is anything specific we can do.

**Comment by dillan-p** [comment]
@wparad yh i followed the maze of posts that spawned off that to no avail, was hoping that someone knew the answer. if i found out will post the solution in here

**Comment by hzhengran** [comment]
Does this help?
`<add key="serilog:write-to:AmazonCloudWatch.logEventRenderer"
  value="{namespace}.JSONLogEventRenderer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />`

**Comment by thoean** [comment]
The latest version (4.0.119, and the current readme in master contain detailed information on how to configure the library.

I'm closing this issue. Please report back in case there's anything we missed.
