### ISSUE TITLE
Still not getting AWS config

### ISSUE THREAD

**Issue by timhargan** [Cimpress-MCP/serilog-sinks-awscloudwatch#58]
even though i made the suggested changes in #57, it still throws an exception saying it cant find the credentials.  I have 3 amazon services that are all currently using the configuration fine.  So it is not the AWS config that is not correct.

**Comment by timhargan** [comment]
Do you have an example of a appsettings.json where dependency injection is used in the code? (servicecollection)

**Comment by wparad** [comment]
(This is not a support ticket system, please do not create extra issues)  I am closing this issue, if you still have comments please add them to #57.
