### ISSUE TITLE
Set the default log level to be LevelAlias.MinimumLevel

### ISSUE THREAD

**Issue by abbotware** [Cimpress-MCP/serilog-sinks-awscloudwatch#62]
shouldnt the default log level match the logging infrastructure already?

the following code:  the file and console are both writing debug / verbose values.  Cloudwatch sink  however, is not honoring this setting... 

```
        // options for the sink, specifying the log group name
        CloudWatchSinkOptions options = new CloudWatchSinkOptions { LogGroupName = logGroupName};

   Log.Logger = new LoggerConfiguration()
            .ReadFrom.Configuration(configuration)
            .MinimumLevel.Verbose()
            .Enrich.FromLogContext()
            .WriteTo.Console()
            .WriteTo.AmazonCloudWatch(options, client)
            .WriteTo.RollingFile("serilog.txt", outputTemplate: "{Timestamp} [{Level}] ({CategoryName:l}) {Message}{NewLine}{Exception}", shared: true)
            .CreateLogger();
```

**Comment by wparad** [comment]
Yes, it should take the value from the `LoggerConfiguration` instead of using it's own value.  I'm not sure why events are being sent to the Sink however, if the Configuration already is filtering them.  It sounds like there are two problems here.  For the sink we can set the default to be the same as the one set in the Configuration, assuming that is available.  But there is a second problem is that is "Why does Serilog ignore the MinimumLevel when sending logEvents to a Sink? "  and that question, you'll have to take to the main repository.

**Comment by abbotware** [comment]
I was thinking you could make it a nullable propert.  Then if you "new" up CloudWatchSinkOptions it wont get a value unless its explictly set - but removing it might have the same net effect if it is not needed.

I am fairly new to Serilog: but, im not sure there is a problem with Serilog since 2 of the 3 "WriteTo" get the data as expected.  I did take me a while to even realize that CloudWatchSinkOptions might be an issue - i peeked at the source code and thats kinda where i saw informational set to the default value.

**Comment by wparad** [comment]
I see what is going on here.  The default for the logger is set at a higher level than the configuration here.  So while the other two loggers default the lowestLogLevel to be `LogEventLevel.Verbose`, this sink specifies the `LogEventLevel.Informational`.

This Sink **IS** honoring the setting, it just is also further restricting it.  If instance you set the global logging level at `Error` then you would only get those, the sink isn't overriding, it is a second filter.

What can we do?  We'll we could change the default to also be Verbose as those other two loggers specify.  However, I'm wondering if you really want all the Debug and Verbose messages in CloudWatch Logs, they might be great for debugging locally, but I'm hesistant to release a new version of the library just to change the default.

Given that analysis, I'm going to close this issue (as it isn't really an issue).  But I will update the readme.md to point out what the default logging level is.

**Comment by abbotware** [comment]
FYI - an asp net core application running in AWS Elastic Beanstalk web site has **no console** or **file logging** capabilites (file system has not write permissions) - so yes I DO want all those verbose messages going to cloudwatch! -  I currently have an open bug report with another project (SignalR) and have been struggling to get diagnostic data out of AWS / EB.
