### ISSUE TITLE
Comparison to aws-logging-dotnet

### ISSUE THREAD

**Issue by justinhelgerson** [Cimpress-MCP/serilog-sinks-awscloudwatch#63]
I'm looking for a logging solution for my .NET Core app while running in AWS EB.  What features does this library provide in comparison to the official one from [AWS](https://github.com/aws/aws-logging-dotnet)?

**Comment by wparad** [comment]
You are more than welcome to review the code, fundamentally this is a Serilog logger, while it seems the "official" ones from AWS do not support Serilog.
