### ISSUE TITLE
Include a sample using configuration from appsettings.json

### ISSUE THREAD

**Issue by pontusr** [Cimpress-MCP/serilog-sinks-awscloudwatch#74]
Thanks for your work.

We depend on .Net Core configuration to configure the log group. Could you provide a working sample for this or consider updating the readme or wiki on how to achieve this? I've tried many approaches but since SeriLog's SelfLog doesn't log exceptions from JSON configurations I'm in the dark here.

Any help would be much appreciated - I'd be happy to contribute a PR once I understand how it works if it helps.

**Comment by thoean** [comment]
Hi @pontusr ,

this is the relevant part of the readme:

```csharp
// options for the sink defaults in https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/blob/master/src/Serilog.Sinks.AwsCloudWatch/CloudWatchSinkOptions.cs
var options = new CloudWatchSinkOptions
{
  // the name of the CloudWatch Log group for logging
  LogGroupName = logGroupName,
  // the log stream provider
  LogStreamNameProvider = new DefaultLogStreamProvider(),
};
```

So the log group name can be provided as part of the options, and you can then also provide a custom log stream provider. See 2 implementations of a log stream provider [here](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/tree/master/src/Serilog.Sinks.AwsCloudWatch/LogStreamNameProvider). If they don't satisfy your needs, you could implement your own and provide that as part of the options.

Does that answer your question?

**Comment by pontusr** [comment]
Sorry for not being clear enough - we want to log the bootstrapping of the application for when the configuration object isn't available yet, very similar to this sample: https://github.com/serilog/serilog-aspnetcore/blob/dev/samples/SimpleWebSample/Program.cs

So I'm looking for a way to configure the LogGroupName in our appsettings.json file.

**Comment by thoean** [comment]
I don't have the fully working example at hand - but does the documentation [in our readme](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch#configuration-via-config-file) help to get you started, and look at specific examples in the `Serilog.Settings.Configuration`  project on GitHub?

**Comment by pontusr** [comment]
We are using Serilog.Settings.Configuration successfully for many sinks, but it seems to me that the recent changes to this sink to provide a single CloudWatchSinkOptions object instead of the parameters directly doesn't play nicely with the Serilog.Settings.Configurations conventions.

I haven't spent time looking at the source code yet but here's a few things I've found while attempting to get this to work. 

A Serilog.Settings.Configuration Configuration requires a Name property which is missing from the code snippet in the readme.md - but I can infer that it should be `AmazonCloudWatch`.

It also seems from the Code First configuration snippets that an AmazonCloudWatchLogsClient should be supplied, but that is also missing from the snippet - or am I mistaken?

I would very much appreciate any hints on how to move forward.

**Comment by thoean** [comment]
As mentioned, I don't have such a snipped ready, and I'm not very familiar regarding the `Serilog.Settings.Configuration` library. @wparad might have hints from the time when he added that to the readme.

I think it's good input to extend the example. That said, the question is potentially also to be asked in the `Serilog.Settings.Configuration` library to make a full suite of samples on how objects can be constructe and constructors can be invoked.

**Comment by pontusr** [comment]
Thanks for your help!
I only came back to this today. While I am now able to configure the options using an `appsettings` file and `Serilog.Settings.Configuration` I'm not able to provide the Cloudwatch client in the same way due to the lack of an interface similar to `CloudWatchSinkOptions`.
For now, I've been able to resolve our needs using https://github.com/aws/aws-logging-dotnet which actually provides a Serilog sink as well. However - they do lack some other options so I'm still hoping this library would be able to add such a feature in the future.

**Comment by DouglasHammon** [comment]
@pontusr Did you find a solution for this?

**Comment by wparad** [comment]
@pontusr, @DouglasHammon,

Manually creating the CloudWatchLogsClient shouldn't be strictly necessary. The library will automatically create one with the already configured credentials according to the registered credentials and configuration providers.

That means if using the `default` profile or the environment variables, this works out of the box. If using decrypted in-process credentials, or another mechanism is is slightly more complicated but still is easy to achieve.

The best reference for how to do this is available in the [AWS C# SDK documentation for credentials](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html#creds-locate)
