### ISSUE TITLE
Unable to Write Logs to an Existing Log Stream

### ISSUE THREAD

**Issue by thirsh** [Cimpress-MCP/serilog-sinks-awscloudwatch#75]
The first time my application runs, the configured CloudWatch sink creates the AWS Log Stream and outputs log content as expected.  I am using an EC2 Instance Id for the stream name.  I would like all subsequent log content for this EC2 Instance to go to the same log stream.  If I run my application again, using the same instance id for the stream name, Serilog reports the following error in its SelfLog:

> Error initializing log stream. No logs will be sent to AWS CloudWatch. Exception was Amazon.CloudWatchLogs.Model.ResourceAlreadyExistsException: The specified log stream already exists

Of course it exists, but shouldn't I be able to append to it?  I have tried setting the `CreateLogGroup` property to `true` and `false` in my `CloudWatchSinkOptions`, but the result is the same exception.

**Comment by thoean** [comment]
Hi @thirsh . I can confirm this behavior, and also that it's the intent to do this in this library. See the [related code](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/blob/master/src/Serilog.Sinks.AwsCloudWatch/CloudWatchLogSink.cs#L148), which assumes a new one can be generated by using unique names.

This library has various exception handling around "something went wrong with sending it to the stream". It then simply creates a new stream - typically re-using the same name, but with a guid attached to it.

That said, I understand your desire. I suggest the following things:
* It'd be good to know why you want the same name, as opposed to just the same prefix. See for example the [ConstantLogStreamNameProvider.cs](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/blob/master/src/Serilog.Sinks.AwsCloudWatch/LogStreamNameProvider/ConstantLogStreamNameProvider.cs).
* If you want to look towards a solution, please verify if it's technically feasible to concurrently write to the same log-stream from two different applications, and having the `sequenceToken` updated correctly. (I never tried this myself.)
  * If that's possible, do you want to come up with a pull request enhancing the `CreateLogStreamAsync` method in a similar way than we have the `CreateLogGroupAsync`?

I hope that helps us better understand your request and move towards a solution for your needs - either by not needing it, or by providing it as part of this library if it's technically feasible.

**Comment by thoean** [comment]
You're not doing anything wrong. See [the code where we create the log stream](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/blob/master/src/Serilog.Sinks.AwsCloudWatch/CloudWatchLogSink.cs#L148). That doesn't check whether the log stream already exists. For the log group, [we do this check](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/blob/master/src/Serilog.Sinks.AwsCloudWatch/CloudWatchLogSink.cs#L110).

In case you want to have a single log stream, there's a limitation: You cannot have multiple processes writing to the same log stream. The next sequence token will always be wrong. In your case, that might work.

I think the best is to:
* Extend the `ILogStreamNameProvider` with a new property like `IsUniqueName`, and default all of the existing implementations in this library to `true`.
* Leverage that flag to check whether the log stream should always be created in the `CloudWatchLogSink`, and if it's `false`, do the check whether it's already exists.
* Be very clear in the documentation what that would mean to avoid support-type requests on this library that are not bugs, but just how CloudWatchLogs work.

Do you want to come up with a pull request?

**Comment by thirsh** [comment]
Yes, I'd be glad to contribute.  I should have a pull request in a week or so, maybe sooner.

**Comment by thoean** [comment]
Sounds good. Thanks!
