### ISSUE TITLE
CloudWatchSinkOptions comments are not shipped in the NuGet

### ISSUE THREAD

**Issue by krdmllr** [Cimpress-MCP/serilog-sinks-awscloudwatch#82]
Hi,

i noticed that the property comments of the CloudWatchSinkOptions are missing. Is it possible that you dont ship the XML documentation in the nuget package?

**Comment by wparad** [comment]
It seems they aren't included right now, I don't think that was intentional to leave them out, feel free to put up a PR to support that.

**Comment by krdmllr** [comment]
Pr is open https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/pull/83.
Out of curiosity, is the global.json required for appveyor to work or is there another reason why the specfic dotnet core version is required?

**Comment by wparad** [comment]
Probably just to make it easier to do development, since not all developers have the same dotnet core version installed or use that one by default. So when using the `global.json` it will automatically pull in the right one.
