### ISSUE TITLE
MyCustomTextFormatter is not clear in documentation

### ISSUE THREAD

**Issue by nkimadusanka** [Cimpress-MCP/serilog-sinks-awscloudwatch#86]
Less information about TextFormatter attribute that passes to the CloudWatchSinkOptions class.

**Comment by wparad** [comment]
There is limited documentation here because the interface `ITextFormatter` is provided by Serilog not by this package. I'll link the relevant Serilog documentation here: https://github.com/serilog/serilog/wiki/Formatting-Output#formatting-json
