### ISSUE TITLE
Request for SetLogStreamName() Function

### ISSUE THREAD

**Issue by csg-kdeepak** [Cimpress-MCP/serilog-sinks-awscloudwatch#91]
The StreamName is set to a default value. I have an application that runs as ECS task. In that case the default stream name is prefix-name/container-name/ecs-task-id, as per AWS doco.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html

This is causing problem as some of the output coming from the other libs are going into the Default AWS stream, but the serilog output is going into the other stream.

I do not find an option to set the streamname while creating the Serilog instance.
Requesting to add support for the same.

**Comment by thoean** [comment]
I might misunderstand your request, but I think that's supported.

From the [documentation](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch#configuration-via-code-first), you can specify a `LogStreamNameProvider`. See the interface and two implementations of it [here](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/tree/master/src/Serilog.Sinks.AwsCloudWatch/LogStreamNameProvider) - you can then also bring your own.

Again, I might misunderstand what you're asking for - so thanks for your thoughts whether that could solve your needs.

**Comment by csg-kdeepak** [comment]
Yeah, you are right. I missed that.
I have created my own Provider and it works just fine.

**Comment by thoean** [comment]
Excellent! Glad it worked as intended.
