### ISSUE TITLE
Custom Formatter Class Provided through the Serilog Section of the appsettings.json doesn't work.

### ISSUE THREAD

**Issue by MKGAURAB** [Cimpress-MCP/serilog-sinks-awscloudwatch#94]
If one provides Custom Written Formatter class and provide with the  `{
    "Serilog": {
        "Using": [ "Serilog.Sinks.AwsCloudWatch" ],
        "MinimumLevel": "Verbose",
        "WriteTo": [            
            {
                "Name": "AmazonCloudWatch",
                "Args": {
                    "logGroup": "your-app",
                    "logStreamPrefix": "environment/component",
                    "restrictedToMinimumLevel": "Verbose",
                    "formatter": "{Namespace}.Customforamtter, {Assembly}"
                }
            }
        ]
    }
  }`
Then it is ignored and rather the Default JSON formatter is used. While the same formatter works with File and other sink.

**Comment by thoean** [comment]
I don't have recent experience on how the JSON-based configuration needs to look like. However, when I cross-check this [with the source code](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/blob/master/src/Serilog.Sinks.AwsCloudWatch/AwsCloudWatchConfigurationExtension.cs#L134), then the parameter is called `textFormatter`, not `formatter`. Also, the extension methods have many additional (optional) arguments, and I don't know if all need to be provided, or only the ones that are required.

**Comment by MKGAURAB** [comment]
> I don't have recent experience on how the JSON-based configuration needs to look like. However, when I cross-check this [with the source code](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/blob/master/src/Serilog.Sinks.AwsCloudWatch/AwsCloudWatchConfigurationExtension.cs#L134), then the parameter is called `textFormatter`, not `formatter`. Also, the extension methods have many additional (optional) arguments, and I don't know if all need to be provided, or only the ones that are required.

Got it. With 'textFormatter' it's working perfectly. Just checked.
