### ISSUE TITLE
AWSSDK.Core nuget package version conflicts

### ISSUE THREAD

**Issue by Andy-DFN** [Cimpress-MCP/serilog-sinks-awscloudwatch#95]
Hi Guys,

Our project is making use of this library for logging to cloudwatch, alongside other AWS functionality. When installing the latest nuget package versions for other AWS libraries, I am recieving a package conflict for AWSSDK.Core as the current version of AWSSDK.CloudWatchLogs package referenced in this library does not support the latest AWSSDK.Core.

This results in package downgrades required for our project to make use of the serilog-sinks-awscloudwatch package.

The nuget package reference for AWSSDK.CloudWatchLogs should be updated to the latest version (3.5.0.9). This should not be a breaking change and should be a simple change to update package versions.

I can raise a PR to do this change if this GitHub is still active for new deployments.

Regards,
Andy W

**Comment by thoean** [comment]
We don't use it internally anymore that much - but happy to accept a pull request and get this merged. Please do some extra testing to ensure things don't break, but it should be a straight-forward change that'd be valuable for the community.

**Comment by Andy-DFN** [comment]
@thoean Thanks for the quick reply.

No problem, I will get a PR raised when I have some time this week.

Regards,
Andy W

**Comment by Andy-DFN** [comment]
I have raised a PR here:
https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch/pull/96

Also worth nothing that the update to AWS SDK v3.5 has no impact at all if already on .net framework or core:
https://aws.amazon.com/blogs/developer/aws-sdk-for-net-v3-5-preview/

**Comment by thoean** [comment]
Fixed as part of #96
