### ISSUE TITLE
Strong name for the assembly

### ISSUE THREAD

**Issue by iravanchi** [Cimpress-MCP/serilog-sinks-awscloudwatch#98]
The assembly in the NuGet package doesn't have a strong name, which makes it much harder to be referenced from projects with assembly signing (need to hack a strong name in the DLL)

It would be nice to have that in the published NuGet package, other assemblies that I came along in the Serilog projects all have strong names.

**Comment by wparad** [comment]
The explicit recommendation from microsoft is to not add this unless it is explicitly necessary by the libraries use case. Since we don't know have a need for it, we don't add it.

![image](https://user-images.githubusercontent.com/5056218/103900179-ca883380-50f7-11eb-85fd-b0402efabd81.png)
![image](https://user-images.githubusercontent.com/5056218/103900200-d116ab00-50f7-11eb-82ec-493078d52725.png)

For more information: https://github.com/dotnet/runtime/blob/master/docs/project/strong-name-signing.md

Please include your necessary use case that we can figure out if it makes sense to support it in the library.

**Comment by iravanchi** [comment]
In my case, I'm referencing it from a library that needs to be signed (since one of the usages need a strong name because of deployment model used in it.)

But in general, having an unsigned assembly limits the usage to only being referenced by assemblies and executables that are never to be signed ever. Since the DLL cannot be referenced from anything that has a strong name. It makes sense for a general-purpose library such as this one to be signed, since you're not sure about how it is going to be used and having an assembly without a strong name limits the usage. That's the same reason all .NET Core libraries use a strong name (as per document you mentioned), and as far as I can see, the rest of the Serilog assemblies also have a strong name. (At least the ones that I've used so far)

Obviously this is not a means for security, the only reason causing a library to have a strong name is to be able to reference it from another assembly with strong name.

**Comment by wparad** [comment]
> In my case, I'm referencing it from a library that needs to be signed (since one of the usages need a strong name because of deployment model used in it.)
> 
> But in general, having an unsigned assembly limits the usage to only being referenced by assemblies and executables that are never to be signed ever. Since the DLL cannot be referenced from anything that has a strong name. It makes sense for a general-purpose library such as this one to be signed, since you're not sure about how it is going to be used and having an assembly without a strong name limits the usage. That's the same reason all .NET Core libraries use a strong name (as per document you mentioned), and as far as I can see, the rest of the Serilog assemblies also have a strong name. (At least the ones that I've used so far)
> 
> Obviously this is not a means for security, the only reason causing a library to have a strong name is to be able to reference it from another assembly with strong name.

Right, but you only quoted me the definition of what a strong name is and does, and didn't actually answer the question. Can you try again, and this time share:

_What is your use case that needs a strong name for this assembly_

**Comment by iravanchi** [comment]
To be brief and to the point: I want to use Serilog (along with this library) in a code, that is being referenced from a project that uses strong names and I don't have a control over, so I am obliged to sign my DLL and I can't do that if I'm referencing something that doesn't have a strong name.

**Comment by wparad** [comment]
So here's a problem, I can't figure out how to generate a valid key on linux. Which is going to prevent us from being able to do this. However, if you would be willing to create the `keyfile.snk` and throw it into a PR and along with adding the necessary attributes to the assemblies I don't see any reason to not merge it.
